# .slsa-goreleaser.yml
version: 1.0

builds:
  - id: process-net-exporter
    goos: linux
    goarch: amd64
    main: ./
    ldflags:
      - "-X main.version={{ .Version }} -X main.buildTime={{ .Timestamp }} -X main.commitHash={{ .GitCommit }}"
    binary: process-net-exporter

release:
  github:
    name_template: "process-net-exporter-{{ .Version }}"

# Metadata that will be included in the provenance file
metadata:
  version: "{{ .Version }}"
  timestamp: "{{ .Timestamp }}"
  commit_hash: "{{ .GitCommit }}"