# example config
processes = ["nginx", "mysql", "redis"]

# Port for the exporter to listen on (optional)
#exporter_port = "8080"

# Address to bind the exporter (optional)
#exporter_addr = "192.168.1.1"